run:
  skip-dirs:
    - pkg/devto

linters:
  enable-all: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - scopelint
      text: Using the variable on range scope `(tc|tt)` in function literal
