name: main
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Set up golangci-lint
        uses: "actions-contrib/golangci-lint@master"
        with:
          args: "run -v"
